// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnownAs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LookingFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("API.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("API.Entities.GeoTocka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DDLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("DDLon")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("FID")
                        .HasColumnType("int");

                    b.Property<int>("IdJavnegaObjekta")
                        .HasColumnType("int");

                    b.Property<string>("JavniObjektSifraJavnegaObjekta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OZN_obj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ozn_tock")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIFKO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ST_stevilka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifraMerilnegaMesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifraObjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Zaporedje")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdJavnegaObjekta");

                    b.HasIndex(new[] { "SifraObjekta" }, "IX_SifraObjekta");

                    b.ToTable("GeoTocke");
                });

            modelBuilder.Entity("API.Entities.MerilnoMesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dobavitelj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DobaviteljNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Energent")
                        .HasColumnType("int");

                    b.Property<string>("EnergentTip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdJavnegaZavoda")
                        .HasColumnType("int");

                    b.Property<int>("IdStavbe")
                        .HasColumnType("int");

                    b.Property<decimal?>("NadmorskaVisina")
                        .HasColumnType("decimal(7,4)");

                    b.Property<string>("NazivJavnegaObjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObracunskaMoc")
                        .HasColumnType("int");

                    b.Property<string>("Ogrevanje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OgrevanjeId")
                        .HasColumnType("int");

                    b.Property<string>("OgrevanjeOznaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifraJavnegaObjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StMerilnegaMesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ZemljepisnaDolzina")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal?>("ZemljepisnaSirina")
                        .HasColumnType("decimal(7,4)");

                    b.HasKey("Id");

                    b.HasIndex("IdStavbe");

                    b.ToTable("MerilnaMesta");
                });

            modelBuilder.Entity("API.Entities.MojElektro.MojElektro15MinMeritev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Blok")
                        .HasColumnType("int");

                    b.Property<decimal>("Energija_A_minus")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("Energija_A_plus")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("Energija_R_minus")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("Energija_R_plus")
                        .HasColumnType("decimal(7,4)");

                    b.Property<int>("IdMerilnegaMesta")
                        .HasColumnType("int");

                    b.Property<int>("IdMerilnegaMestaMojElektro")
                        .HasColumnType("int");

                    b.Property<int>("Leto")
                        .HasColumnType("int");

                    b.Property<string>("LetoDanUra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LetoMesec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LetoMesecBlok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LetoTedenDan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LetoTedenDanUra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mesec")
                        .HasColumnType("int");

                    b.Property<decimal>("OddanaDelovnaMoc")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("OddanaJalovaMoc")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("PrejetaDelovnaMoc")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal>("PrejetaJalovaMoc")
                        .HasColumnType("decimal(7,4)");

                    b.Property<string>("StMerilnegaMesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdMerilnegaMestaMojElektro");

                    b.HasIndex(new[] { "StMerilnegaMesta", "TimeStamp" }, "IX_StMerilnegaMesta_TimeStamp");

                    b.ToTable("MojElektro15MinMeritve");
                });

            modelBuilder.Entity("API.Entities.MojElektro.MojElektroMerilnoMesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Dobavitelj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnotniIdentifikator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GsrnMM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdJavnegaObjekta")
                        .HasColumnType("int");

                    b.Property<string>("NNizvod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivJavnegaObjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RTP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNizvod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifraJavnegaObjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdJavnegaObjekta");

                    b.ToTable("MojElektroMerilnaMesta");
                });

            modelBuilder.Entity("API.Entities.Odcitek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DOEnergijaEuro")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("DOObracunskaMocEuro")
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTime>("DatumOdcitka")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ELEEnergijaEUR")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("ELEOmreznina")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("ELEPrispevki")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("EleJalovaEnergija")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("EleenergijaET")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("EleenergijaMt")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("EleenergijaVt")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("EleobracunskaMoc")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("ElkoLbUnpEnergijskiEkvivalent")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("ElkoLbUnpEnotaMere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ElkoLbUnpKolicina")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("EnergentTip")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Energija")
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("IdJavnegaObjekta")
                        .HasColumnType("int");

                    b.Property<int>("IdMerilnegaMesta")
                        .HasColumnType("int");

                    b.Property<decimal?>("KANALCCNOmrezninaEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("KANALCiscenjeVodeEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("KANALKanalscinaEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("KANALOmrezninaEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("KANALZnesek")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("LetoMesec")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NazivMerilnegaMesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ObdobjeStoritveDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ObdobjeStoritveOd")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PLINDistribucija")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("PLINOdjemnaMoc")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("PLINPorabaKWh")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("PLINPrispevki")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("PLINSkupajBruto")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("PLINZemeljskiPlin")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("SMETIEmbalazaEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("SMETIObdelavaBioEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("SMETIObdelavaMKOEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("SMETIOdlaganjeMKOEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("SMETIOpomba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SMETIPapirKartonEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("SMETIZbiranjeBioEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("SMETIZbiranjeMKOEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("SMETIZnesek")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("StMerilnegaMesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StevilkaRacuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipOgrevanja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipOgrevanjaOznaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("VODAOmrezninaEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("VODAPorabaM3")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("VODAPrispevekEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("VODAVodarinaEur")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("VODAZnesek")
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("Znesek")
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnergentTip");

                    b.HasIndex("IdJavnegaObjekta");

                    b.HasIndex("IdMerilnegaMesta");

                    b.HasIndex("LetoMesec");

                    b.HasIndex("StMerilnegaMesta");

                    b.ToTable("Odcitki");
                });

            modelBuilder.Entity("API.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("API.Entities.PhotoStavbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StavbaId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StavbaId");

                    b.ToTable("PhotosStavbe");
                });

            modelBuilder.Entity("API.Entities.Stavba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("KatastrskaObcinaIme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KatastrskaObcinaSifra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KlasifikacijaCcSi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KlasifikacijaNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KlimatskiKraj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KondicioniranaPovrsina")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("LetoIzgradnje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LetoObnove")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NTP_NetoTloris")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("NadmorskaVisina")
                        .HasColumnType("decimal(7,4)");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivEnote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ogrevanje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrevanjeDrugi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OgrevanjeId")
                        .HasColumnType("int");

                    b.Property<string>("OgrevanjeOznaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opomba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parcele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ParcelePovrsina")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("PovrsinaAplikacija")
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("ProjekcijaTloris")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("ST_OBJ_Gurs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifraJavnegaObjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("StavbaDaNe")
                        .HasColumnType("bit");

                    b.Property<string>("StavbaDel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StavbaStevilka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UlicaHs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("UporabnaPovrsina")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("VrstaObjekta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VrstaObjektaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ZemljepisnaDolzina")
                        .HasColumnType("decimal(7,4)");

                    b.Property<decimal?>("ZemljepisnaSirina")
                        .HasColumnType("decimal(7,4)");

                    b.HasKey("Id");

                    b.ToTable("Stavbe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("API.Entities.AppUserRole", b =>
                {
                    b.HasOne("API.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Entities.GeoTocka", b =>
                {
                    b.HasOne("API.Entities.Stavba", "Stavba")
                        .WithMany("GeoTocke")
                        .HasForeignKey("IdJavnegaObjekta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stavba");
                });

            modelBuilder.Entity("API.Entities.MerilnoMesto", b =>
                {
                    b.HasOne("API.Entities.Stavba", "Stavba")
                        .WithMany("MerilnaMesta")
                        .HasForeignKey("IdStavbe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stavba");
                });

            modelBuilder.Entity("API.Entities.MojElektro.MojElektro15MinMeritev", b =>
                {
                    b.HasOne("API.Entities.MojElektro.MojElektroMerilnoMesto", "MerilnoMestoMojElektro")
                        .WithMany("Meritve15min")
                        .HasForeignKey("IdMerilnegaMestaMojElektro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MerilnoMestoMojElektro");
                });

            modelBuilder.Entity("API.Entities.MojElektro.MojElektroMerilnoMesto", b =>
                {
                    b.HasOne("API.Entities.Stavba", "Stavba")
                        .WithMany("MojElektroMerilnaMesta")
                        .HasForeignKey("IdJavnegaObjekta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stavba");
                });

            modelBuilder.Entity("API.Entities.Odcitek", b =>
                {
                    b.HasOne("API.Entities.MerilnoMesto", "MerilnoMesto")
                        .WithMany("Odcitki")
                        .HasForeignKey("IdMerilnegaMesta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MerilnoMesto");
                });

            modelBuilder.Entity("API.Entities.Photo", b =>
                {
                    b.HasOne("API.Entities.AppUser", "AppUser")
                        .WithMany("Photos")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("API.Entities.PhotoStavbe", b =>
                {
                    b.HasOne("API.Entities.Stavba", "Stavba")
                        .WithMany("PhotosStavbe")
                        .HasForeignKey("StavbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stavba");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("API.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("API.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("API.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("API.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("API.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("API.Entities.MerilnoMesto", b =>
                {
                    b.Navigation("Odcitki");
                });

            modelBuilder.Entity("API.Entities.MojElektro.MojElektroMerilnoMesto", b =>
                {
                    b.Navigation("Meritve15min");
                });

            modelBuilder.Entity("API.Entities.Stavba", b =>
                {
                    b.Navigation("GeoTocke");

                    b.Navigation("MerilnaMesta");

                    b.Navigation("MojElektroMerilnaMesta");

                    b.Navigation("PhotosStavbe");
                });
#pragma warning restore 612, 618
        }
    }
}
